version: "3"
networks:
  net1:
services:
  mydbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    networks:
      - net1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: nhm
      MYSQL_PASSWORD: nhmpass
      MYSQL_DATABASE: mydb

  wpos:
    image: wordpress:5.1.1-php7.3-apache
    depends_on:
      - mydbos
    ports:
      - 8080:80
    volumes:
      - wp_storage:/var/www/html
    restart: always
    links:
      - mydbos:mysql
    networks:
      - net1
    environment:
      WORDPRESS_DB_HOST: mydbos:3306
      WORDPRESS_DB_USER: nhm
      WORDPRESS_DB_PASSWORD: nhmpass
      WORDPRESS_DB_NAME: mydb
volumes:
  mysql_storage:
  wp_storage:
